server:
  port: 8082

spring:
  application:
    name: order-service
  config:
    import: "configserver:"

  main:
    lazy-initialization: true

feign:
  client:
    config:
      default:
        decode404: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
